### ISSUE TITLE
Can't join a session or create one

### ISSUE THREAD

**Issue by marcos-chafer** [mistweaverco/bananas#25]
Hello, I've installed the application using .deb packes in both of my computers (Let's say computer A and computer B, for example) running Kubuntu 24.04.

After installing, in computer A I run the app from the applications menu and host a session, then copy my string through ssh to computer B. In computer B I copy the string from the new file I've created, the textbox turns green and I click connect, but nothing happens.

In computer B I can't even host a session. Maybe it's just computer's B problem?

I've quickly tried looking for a log, but I didn't find any.

**Comment by gorillamoe** [comment]
Does Computer B have an active audio recording device / microphone attached (and active)?
If not, that is the problem. I already pushed the fix for it, but did not release it yet.

**Comment by gorillamoe** [comment]
Maybe fixed in latest v0.0.13 with audio//mic being optional.

Please re-home if the issue persists.
