### ISSUE TITLE
Bug: Cannot Host or Join a session if no mic is available

### ISSUE THREAD

**Issue by madeus** [mistweaverco/bananas#5]
Hi,

I wanted to test it, but unfortunately it doesn't work (for me). I click the "Start a new session" button and nothing happens. I'm not sure, but the logs seem to be in binary form and I can't read anything from them.

![image](https://github.com/user-attachments/assets/1b7e75d7-c9ce-4454-b9ab-c11ab9672ae4)

OS: MS Windows Server 2022.

**Comment by madeus** [comment]
It works on Win11, on MS Server 2022 neither starting a session nor joining a session works.

**Comment by madeus** [comment]
On MacOS 15.1.1 (bananas 0.0.10) everything works fine.

**Comment by gorillamoe** [comment]
I have some spare PC parts, if @microsoft chimes let's me test this without buying a licence, I probably should be able to fix this, or write documention about what needs to be done in win22 server edition.

Thanks for the tests on win11 and macos 15, @madeus! :heart:

**Comment by gorillamoe** [comment]
Maybe this could be related to Bananas assuming you have a microphone and immediately requesting access to it.

Can you elaborate on that? Do you have a microphone attached and active?

**Comment by gorillamoe** [comment]
Is the windows server having a microphone active? Might be an issue that microphone access is a requirement at the moment

**Comment by gorillamoe** [comment]
> > Is the windows server having a microphone active? Might be an issue that microphone access is a requirement at the moment
> 
> This is a VM, there are no audio devices there. ;-)

Perfect, then the fix is easy on my part.

**Comment by jaisongreen** [comment]
> Maybe this could be related to Bananas assuming you have a microphone and immediately requesting access to it.
> 
> Can you elaborate on that? Do you have a microphone attached and active?

I have a microphone port, but nothing was plugged into it. Plugging something into it fixed the issue.

**Comment by gorillamoe** [comment]
I'll make Audio transmission optional in the next release, so this should then be fixed.
